### ISSUE TITLE
Aster show page has a link to zip that is used to import a GeoTiff

### ISSUE THREAD

**Issue by little9** [curationexperts/aster#25]
ACCEPTANCE CRITERIA
------------------------------
- [x] There is a link to the zip that is used to import a GeoTiff into Iris on the Aster show page

**Comment by little9** [comment]
This depends on curationexperts/iris#66 being completed

**Comment by val99erie** [comment]
I think this is complete after curationexperts/iris#66.  See notes in story #27 as well.
