### ISSUE TITLE
Wireframe and Style Guide for UCSB GeoBlacklight site

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/aster#3]
Time bound to 8 hours
- [x] Wireframe for homepage
- [x] Decide colors
- [x] Get header logo

NOTE:  This is just to acquire assets for very minimal styling.  UCSB may wish to do additional design work later.

See #4 for implementation

**Comment by little9** [comment]
![screenshot-2018-3-16 blacklight](https://user-images.githubusercontent.com/4324761/37537301-1b4cc860-291b-11e8-9f25-7c252e40e64e.png)
![screenshot-2018-3-16 china - blacklight search results](https://user-images.githubusercontent.com/4324761/37537302-1b5cefc4-291b-11e8-9f91-393cbc1f3b0b.png)
