### ISSUE TITLE
Build a schedulable process to index works into GeoBlacklight

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/aster#5]
- [ ] The process can be run periodically via a scheduler
- [ ] The process detects new or updated works in the GeoWorks repository data
- [ ] The process builds appropriate entries for the GeoBlacklight index
- [ ] The process updates the GeoBlacklight index

**Comment by val99erie** [comment]
Is it a requirement that this is a scheduled process?  I think we should consider just having the importer for our geo_works app hook into the existing background job for updating the geoblacklight-based app.  And if we need the ability to rebuild the solr index from scratch, we can write a rake task in our geo_works-based app (assuming something like that doesn't already exist)

**Comment by shanitajohn** [comment]
Superseded by #92
